"""change comment column name to content

Revision ID: 883be474b6e1
Revises: ccc3cb3f7837
Create Date: 2025-12-17 18:37:53.273510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '883be474b6e1'
down_revision: Union[str, Sequence[str], None] = 'ccc3cb3f7837'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('content', sa.String(), nullable=True))
    op.drop_column('comments', 'comment')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('comment', sa.VARCHAR(), nullable=True))
    op.drop_column('comments', 'content')
    # ### end Alembic commands ###
