"""change created_at column configs

Revision ID: b0ccdeae6696
Revises: 883be474b6e1
Create Date: 2025-12-17 19:16:23.092297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0ccdeae6696'
down_revision: Union[str, Sequence[str], None] = '883be474b6e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'author_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('author_id', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
